### ISSUE TITLE
flask.cli.NoAppException: Could not import "wsgi".

### ISSUE THREAD

**Issue by prabhakarjuzgar** [lgiordani/flask_project_setup#1]
Hi,

Thanks for the great blog.
I am having trouble executing the part 1. After executing
"docker-compose -f docker/development.yml up -d", going to 0.0.0.0:5000, results in NoAppException.

Can you please let me know how to resolve this? Thanks in advance.

Regards,
Prabhakar

**Comment by lgiordani** [comment]
Hi! Thanks for reading the blog. What you say is very strange, I'm following the blog posts with my some colleagues and everything is working. I read here https://stackoverflow.com/questions/41979427/flask-cli-noappexception-application-crashing that that exception might be a sign of a missing import. Can you run `docker-compose -f docker/development.yml logs web` and see what the logs of the Python application say? I have the hunch there is something wrong in the virtual environment.

**Comment by prabhakarjuzgar** [comment]
Hi,
It is so happening that the workdir is owned by user with id 1001 (on my system it is me), and everything else is owned by root. So when docker is running it is not able to access anything from inside the workdir. I will try your suggestion after office hours. Thanks.

**Comment by prabhakarjuzgar** [comment]
HI,

When the folder on the host is [bind mount](https://docs.docker.com/storage/bind-mounts/), the folder is owned by the user on the host, but the execution in the container is by root, hence the error. When the binding is removed (volumes: ) tag in the compose file, everything works fine.

**Comment by lgiordani** [comment]
Yes, indeed `volumes` is specified in the code.

https://github.com/lgiordani/flask_project_setup/commit/9e08735af6177760cd750230122a507b15c9c112#diff-b020a27fee741b5e10a4d106e6d266ec2bc9a4e694496470529407966142ad35R13

Did I misunderstood your comment sorry?

**Comment by prabhakarjuzgar** [comment]
/flask_project_setup$ docker exec -it flaskprojectsetup_web_1 bash
root@471e3053e50f:/code# cd ..
root@471e3053e50f:/# ls -la
total 0
drwxr-xr-x.   1 root root  17 Jan 19 22:31 .
drwxr-xr-x.   1 root root  17 Jan 19 22:31 ..
-rwxr-xr-x.   1 root root   0 Jan 19 22:31 .dockerenv
drwxr-xr-x.   1 root root 179 Jan 12 03:58 bin
drwxr-xr-x.   2 root root   6 Nov 22 12:37 boot
**drwxr-xr-x.   6 1001 1001 188 Jan 17 19:11 code**
drwxr-xr-x.   5 root root 340 Jan 19 22:31 dev
drwxr-xr-x.   1 root root  66 Jan 19 22:31 etc
drwxr-xr-x.   2 root root   6 Nov 22 12:37 home
drwxr-xr-x.   1 root root  41 Jan 12 03:58 lib
drwxr-xr-x.   2 root root  34 Jan 11 00:00 lib64
drwxr-xr-x.   2 root root   6 Jan 11 00:00 media
drwxr-xr-x.   2 root root   6 Jan 11 00:00 mnt
drwxr-xr-x.   2 root root   6 Jan 11 00:00 opt
dr-xr-xr-x. 376 root root   0 Jan 19 22:31 proc
drwx------.   1 root root  20 Jan 19 22:27 root
drwxr-xr-x.   1 root root  21 Jan 18 17:08 run
drwxr-xr-x.   1 root root  20 Jan 12 03:57 sbin
drwxr-xr-x.   2 root root   6 Jan 11 00:00 srv
dr-xr-xr-x.  13 root root   0 Jan 19 08:35 sys
drwxrwxrwt.   1 root root   6 Jan 19 22:27 tmp
drwxr-xr-x.   1 root root  19 Jan 11 00:00 usr
drwxr-xr-x.   1 root root  19 Jan 11 00:00 var
root@471e3053e50f:/# 

As you can see the workdir is owned by the user and not root. So when I execute 

curl localhost:5001
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
...
...
...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
ModuleNotFoundError: No module named 'wsgi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 338, in __call__
    self._flush_bg_loading_exception()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 326, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 314, in _load_app
    self._load_unlocked()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 250, in locate_app
    raise NoAppException('Could not import "{name}".'.format(name=module_name))
flask.cli.NoAppException: Could not import "wsgi".

-->

Regards,
Prabhakar Juzgar

**Comment by lgiordani** [comment]
OK, the "issue" that you mention is not such. That is the standard setup in Docker containers, and in LInux systems the user `root` can do everything by design, so it definitely would not have issues reading files belonging to another user. The error you have is that `wsgi.py` can't be imported, and I was able to replicate your problem deleting that file. Can you please confirm you have it? Can you show me a list of files in the project directory? Thanks!

**Comment by prabhakarjuzgar** [comment]
[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ ls -la
total 24
drwxr-xr-x. 6 prabhakar prabhakar  188 Jan 17 19:11 .
drwxrwxr-x. 5 prabhakar prabhakar  101 Jan 17 19:34 ..
drwxr-xr-x. 2 prabhakar prabhakar   37 Oct 16 18:25 application
drwxr-xr-x. 2 prabhakar prabhakar   30 Oct 16 18:25 config
drwxr-xr-x. 2 prabhakar prabhakar   47 Oct 16 18:25 docker
-rw-r--r--. 1 prabhakar prabhakar  148 Oct 16 18:25 .flake8
-rwxr-xr-x. 1 prabhakar prabhakar 1543 Oct 16 18:25 manage.py
drwxr-xr-x. 2 prabhakar prabhakar   70 Oct 16 18:25 requirements
-rw-r--r--. 1 prabhakar prabhakar   32 Jan 17 19:11 requirements.txt
-rw-r--r--. 1 prabhakar prabhakar   96 Oct 16 18:25 wsgi.py

**Comment by lgiordani** [comment]
OK, I think I know what is going on. I noticed that when you log into the container you end up in `/code` according to what you posted two messages ago, but the `WORKDIR` of the Docker image should be `/opt/code` which is where we map the project directory. Did you change that setup on purpose or it there a typo in the `Dockerfile`? Can you post your version of that file? Thanks

**Comment by prabhakarjuzgar** [comment]
[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ cat Dockerfile 
FROM python:3

ENV PYTHONUNBUFFERED 1
ENV FLASK_APP=wsgi.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development
ENV FLASK_CONFIG=development
WORKDIR /code
RUN mkdir /code/application
RUN mkdir /code/config
RUN mkdir /code/requirements

COPY ./application/ /code/application/
COPY ./config/ /code/config/
COPY ./requirements/ /code/requirements/
COPY ./wsgi.py wsgi.py

COPY requirements.txt requirements.txt
RUN python3 -m pip install cryptography --no-binary cryptography
RUN python3 -m pip install -r requirements.txt

EXPOSE 5001

CMD ["flask", "run", "--port", "5001"]

**Comment by lgiordani** [comment]
Oh, but this is not the Dockerfile that I describe in the post, sorry. The one I created there is
``` Dockerfile
FROM python:3

ENV PYTHONUNBUFFERED 1

RUN mkdir /opt/code
RUN mkdir /opt/requirements
WORKDIR /opt/code

ADD requirements /opt/requirements
RUN pip install -r /opt/requirements/development.txt
```

You can find it [here](https://www.thedigitalcatonline.com/blog/2020/07/05/flask-project-setup-tdd-docker-postgres-and-more-part-1/#step-4-containers-and-orchestration).
What you are doing is pretty different.

**Comment by prabhakarjuzgar** [comment]
Ok, this is with the same setup that I downloaded from git.

[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ FLASK_ENV="development" FLASK_CONFIG="development" docker-compose -f docker/development.yml build web

FLASK_ENV="development" FLASK_CONFIG="development" docker-compose -f docker/development.yml up -d
Starting docker_web_1 ... done

[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ curl localhost:5000
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">


================================================================================================

[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ ls -la
total 16
drwxr-xr-x. 6 prabhakar prabhakar  144 Oct 16 18:25 .
drwxrwxr-x. 6 prabhakar prabhakar  131 Jan 20 15:28 ..
drwxr-xr-x. 2 prabhakar prabhakar   37 Oct 16 18:25 application
drwxr-xr-x. 2 prabhakar prabhakar   30 Oct 16 18:25 config
drwxr-xr-x. 2 prabhakar prabhakar   47 Oct 16 18:25 docker
-rw-r--r--. 1 prabhakar prabhakar  148 Oct 16 18:25 .flake8
-rwxr-xr-x. 1 prabhakar prabhakar 1543 Oct 16 18:25 manage.py
drwxr-xr-x. 2 prabhakar prabhakar   70 Oct 16 18:25 requirements
-rw-r--r--. 1 prabhakar prabhakar   31 Oct 16 18:25 requirements.txt
-rw-r--r--. 1 prabhakar prabhakar   96 Oct 16 18:25 wsgi.py


-rw-r--r--. 1 prabhakar prabhakar 292 Oct 16 18:25 docker/development.yml
[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ ls -la docker/Dockerfile 
-rw-r--r--. 1 prabhakar prabhakar 194 Oct 16 18:25 docker/Dockerfile
[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ cat docker/Dockerfile 
FROM python:3

ENV PYTHONUNBUFFERED 1

RUN mkdir /opt/code
RUN mkdir /opt/requirements
WORKDIR /opt/code

ADD requirements /opt/requirements
RUN pip install -r /opt/requirements/development.txt
[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ 

===========================================================================================
Inside container -

[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ docker exec -it docker_web_1 bash
root@ecbaea7b9813:/opt/code# cd ..
root@ecbaea7b9813:/opt# ls -la
total 0
drwxr-xr-x. 1 root root  26 Jan 20 15:29 .
drwxr-xr-x. 1 root root  17 Jan 20 15:30 ..
drwxr-xr-x. 6 1001 1001 144 Oct 16 17:25 code
drwxr-xr-x. 1 root root  70 Jan 20 15:29 requirements
root@ecbaea7b9813:/opt# cd code/
root@ecbaea7b9813:/opt/code# ls -la
ls: cannot open directory '.': Permission denied
root@ecbaea7b9813:/opt/code#

**Comment by lgiordani** [comment]
That is exactly the setup I have (save from the user being 1000 but that's not the problem). Can you please confirm that you are using the YAML file I posted and give me details on your system? Which Linux distro (or OS) and which Docker version?

**Comment by prabhakarjuzgar** [comment]
I am exactly using the setup cloned from git. I am using centos-7.

[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ docker --version
Docker version 1.13.1, build 0be3e21/1.13.1

[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ docker-compose --version
docker-compose version 1.18.0, build 8dd22a9


[prabhakar@prabhakar] ~/workspace/prabhakar.juzgar/python/../flask_project_setup$ uname -a
Linux prabhakar.juzgar 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lgiordani** [comment]
Oh CentOS! That explains everything. They run Docker with SELinux enabled. I found a couple of pages about that here http://www.projectatomic.io/blog/2016/07/docker-selinux-flag/ and here https://stackoverflow.com/questions/39487201/permission-denied-in-docker-container-unless-privileged-true. Can you please see if this solves the issue?

**Comment by prabhakarjuzgar** [comment]
Great. Thanks.

**Comment by lgiordani** [comment]
Hi! Thanks for closing this. Would you mind adding here a quick comment on what you had to do? I'd like to add it to the posts (with attribution). Thanks!

**Comment by prabhakarjuzgar** [comment]
Hi Thanks for helping out.
I followed docker installation process as described here -
[here](https://docs.docker.com/engine/install/centos/).

The setup worked out of box after that.
