### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by buttle** [lgiordani/flask_project_setup#2]
Hi,

Wow, this is just what I was looking for! Thank you so much.

I would like to copy your code but I can't find the License, so I don't know if I can.

Could you point me in the right direction please?

Cheers!

**Comment by lgiordani** [comment]
Hi! You are welcome. Well this was created as part of series of posts on my blog (I forgot to mention it in the README), so it falls under the CC BY-SA 4.0 that I use for everything I write there. This basically means that you can use the code as you prefer (and thanks for copying it), provided you mention the source. Now, this is just a simple setup, so I'm not fussed, but if you create videos or other public resources I would appreciate a mention to the blog. Thanks!

The license for the blog is here https://www.thedigitalcatonline.com/pages/about.html

**Comment by buttle** [comment]
If I publish a howto or any other such content I will certainly link to the blog.

CC BY-SA 4.0 is good for the blog content, but it isn't really a software license. Maybe you like [AGPL](http://www.gnu.org/licenses/agpl-3.0.html)?

**Comment by lgiordani** [comment]
Hi! Sorry for the delay. I just added a license and a readme, hope this helps. Have a good day!
